language: node_js
node_js:
- '10'
- '11'
- '12'
- '13'
jobs:
  include:
    matrix:
    - stage: npm release
      if: tag IS present
      node_js: 12
      deploy:
        provider: npm
        email: rogier+npm@konfirm.eu
        on:
          branch: master
          tags: true
        api_key: 
          secure: Fhj/YX4E3yFpim8f6D29EfJjg06TmYMmh2lJAPsqiKwaX0i43bGYg8IzJPslBGjkxIdfzFMedmIb7xip+zmKYnvAZOnG2qVExq6tFyPXaj6eirzgt7BrcelAnIlSCSZqEx3CQyGhyH2z/V7bR9kVy/YAFDH5RAjFD7508wn2jUFvLqWDnopa39YcZrnX0QoA5V/axvUt2asa1OV1LBaHRPjYrVGQSzaeVwnDn3TBrEvAyISyG+ah8zXT9tfOv23y64+owF2eg2HN+AyadpZOWU0C+EzoLcN4zeghPujS6VY3Ux5A2DFS4Y6ROEXJABpDu1EW8Y6ukw80qQYK/vD75CR0KEVV9rfb7xFOOHiOGd0lEIQlnYvux3BND6hJbLVLEgN/LpEi3op3ush+ALVD5v5Dzje5hzbKO4tiKw/sA0djckZW8KdwBwXnO7kbG3/F1w0EncqRUOvFWAtVfbYNWhd5FJhcWDwGfoXdOK9YGUw9afdzlUtEMMz0Ta0sQ9xk+3buLI7Jq5rCb7ZaO3seAflhq5adGP38n29LBIJTepf/AKqLry7voWzzKpZ3y/oCfOxqp87RFN7bUeeHMzFoo30aj7/5RAKj78vDiCj4lz3u1T6/n9RQYDJCaqXlRnAB5E3mg4mJNuxr68DfaXTuvixkOi3FoGdgpLlmL4zdmo8=
